version: "3.7"

services:
  node:
    command: bash -c "sleep infinity"
    build:
      context: .
      args:
        USER_UID: 1000
    environment:
      - SHELL=/bin/bash
      - MONGO_TEST_URL=mongodb://admin:mindgrep@mongodb1,mongodb2,mongodb3:27017/
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/test
      - PORT=4000
    volumes:
      - ..:/workspace/development/app:cached
      - ./scripts:/scripts
    working_dir: /workspace/development/app
    ports:
      - 4000:4000

    depends_on:


      - postgres








  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - postgresql-data:/var/lib/postgresql/data







volumes:


  postgresql-data:





